// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// User represents a row from the users table.
type User struct {
	ID   int32            `json:"id"`
	Name string           `json:"name"`
	Dob  pgtype.Date      `json:"dob"`
}
